### ISSUE TITLE
How to execute an `IfNode` programatically

### ISSUE THREAD

**Issue by bunnymatic** [sass/ruby-sass#105]
I've developed a Gem which pulls the variables from a `colors.scss` file so that an app can quickly dump it on a styleguide page (https://github.com/rcode5/sass_color_extractor).

On a separate Rails app, where we're using this gem, we added an `@if` clause which broke my gem.

I'm trying to figure out how, if there is a way, to analyze/execute an `IfNode` so that my consuming gem can figure out what is going on.

The SCSS looks like this:

```scss
$external-setting: true;

@if $external-setting == true {
  $dynamic-color: blue;
}
@else {
  $dynamic-color: red;
}

```

And my processor is doing the following
```
    DEFAULT_SYNTAX = :scss

    def self.parse_colors(sass_file)
      syntax = guess_syntax(sass_file)
      engine = Sass::Engine.for_file(sass_file, syntax: syntax)
      colors = VariableEvaluator.visit(engine.to_tree).compact.reject{|entry| entry.flatten.empty?}
      Hash[colors.map{|name, color| [ name, color.to_s.gsub(/^#/,'') ]}]
    end

    class << self
      private
      def guess_syntax(file)
        guess = File.extname(file)[1..-1].to_sym
        [:sass, :scss].include?(guess) ? guess : DEFAULT_SYNTAX
      end
    end
```

This code currently fails like this:

```
     NoMethodError:
       undefined method `flatten' for (Sass::Tree::IfNode Sass::Tree::VariableNode):Sass::Tree::IfNode
     # ./lib/sass_color_extractor/base.rb:8:in `block in parse_colors'
     # ./lib/sass_color_extractor/base.rb:8:in `reject'
     # ./lib/sass_color_extractor/base.rb:8:in `parse_colors'
     # ./spec/sass_color_extractor_base_spec.rb:25:in `block (4 levels) in <top (required)>'
```

I wonder if there is a way to process/evaluate this `IfNode` so that the processor could continue.

Thanks, in advance, for any tips/pointers/documentation

**Comment by nex3** [comment]
There's probably no better way to do this than to rewrite or copy whatever subset of the `Perform` visitor you need to get the information you want. It's not really built in a way to factor out subsets of the SassScript functionality for other use-cases.

Also, heads up: Ruby Sass is deprecated and will be completely unmaintained as of the end of March, so building infrastructure around it may not be the soundest plan.

**Comment by bunnymatic** [comment]
cool.  Thanks for the heads up.  I guess it's time to look for another solution.
