### ISSUE TITLE
Bezier Point on Curve function

### ISSUE THREAD

**Issue by FunkyloverOne** [sass/ruby-sass#68]
Hey guys, some time ago I have made my own extension for sass inside one of my Rails projects. But I think that such an extension could be a good use for everyone on any platform, and not only Rails. So here's a code example:
```scss
@keyframes BezierJumpAnimation {
  @for $i from 0 through 100 {
    #{1% * $i} {
      $p: bezier_curve($i / 100, (50 50, -70 -50, -200 60));
      $x: nth($p, 1);
      $y: nth($p, 2);
      transform: translate($x * 1%, $y * 1%);
    }
  }
}
```
And here's what it does: it internally "builds" a Bezier curve using the following 3 points:
`(50 50, -70 -50, -200 60)`, and takes a coordinates of point on "built" curve on step `$i / 100`, e.g. for each percent. In this case it was only for nice parabolic "jump" animation, but it could be used in much & much more use cases, that function may take any amount of control points to build a curve, so it could be very complex curve.
Ruby code I used to build this extension depends on my fork (which is not maintained for now) of not maintained Bezier gem, here's my fork:
https://github.com/FunkyloverOne/beziercurve
And here's actual Ruby code, it's pretty basic:
```ruby
require 'sass'

module Sass::Script::Functions
  module BezierCurve
    def bezier_curve(t, control_points)

      # bunch of validations here
      assert_type t, :Number
      if t.value < 0 || t.value > 1
        raise ArgumentError, "#{t.inspect} should be a float in 0..1"
      end
      unless control_points.is_a?(Sass::Script::Value::List)
        raise ArgumentError, "#{control_points.inspect} is not a list"
      end
      points = control_points.to_a
      points.each do |point|
        unless point.is_a?(Sass::Script::Value::List)
          raise ArgumentError, "#{point.inspect} is not a list"
        end
        unless point.to_a.length == 2
          err = "#{point.inspect} should have only 2 values (X and Y coords)"
          raise ArgumentError, err
        end
      end

      # actual code here
      bez = Bezier::Curve.new(*points.map { |coords| coords.to_a.map(&:value) })
      point = bez.point_on_curve(t.value)
      Sass::Script::List.new(
        [Sass::Script::Number.new(point.x), Sass::Script::Number.new(point.y)],
        ','
      )
    end
    Sass::Script::Functions.declare :bezier_curve,
                                    [:point_on_curve, :control_points]
  end
  include BezierCurve
end
```

So, it's kinda close to be a PR, we just need some specs for it, and your approval of such functionality... And also probably better lib for actual Bezier curve calculation. What do you think guys @nex3, @chriseppstein?

**Comment by FunkyloverOne** [comment]
Oh I didn't see that ruby-sass is deprecated, so it turns out my Ruby code here is no more relevant.

**Comment by nex3** [comment]
From a language perspective, adding a bunch of new built-in functions is something we try to avoid doing unless there's a very significant use-case for it. This is something I'd recommend distributing first as a plug-in library, then possibly considering rolling that into the core language if it's clearly widely used.
