### ISSUE TITLE
[Question] Is Sass gen css var 

### ISSUE THREAD

**Issue by HumanG33k** [sass/ruby-sass#69]
I m pretty new with sass.

Is it generate some css variables ? If not why ?
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

Thx

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
