### ISSUE TITLE
Support CSS min() and max()

### ISSUE THREAD

**Issue by nex3** [sass/ruby-sass#77]
https://github.com/sass/sass/issues/2378

**Comment by LuckehPickle** [comment]
@nex3 I believe you've linked the wrong issue here. It should be [sass/sass#2378](https://github.com/sass/sass/issues/2378). Also, if I can wrap my head around the code base a little I'm happy to try and implement this.

**Comment by nex3** [comment]
> I believe you've linked the wrong issue here. It should be sass/sass#2378.

Fixed, thanks!

> Also, if I can wrap my head around the code base a little I'm happy to try and implement this.

That would be great! [The lexer](https://github.com/sass/ruby-sass/blob/stable/lib/sass/script/lexer.rb) is probably the place to start, since it handles parsing functions like `calc()`.

**Comment by LuckehPickle** [comment]
@nex3 This probably seems like a stupid question... but how do I actually run the program for testing? I've managed to run the tests and make some changes but I have no idea how to try running the project with a Sass file.

**Comment by nex3** [comment]
`ruby bin/sass.rb` should do it.
