### ISSUE TITLE
Ran --precision command with wrong input file, breaks the css output file

### ISSUE THREAD

**Issue by JanaVanMaele** [sass/ruby-sass#79]
I use gulp-sass to compile my css. Now I wanted to change the precision setting of sass and I ran 
`sass --precision 10 app/sass/**/* app/main.css`
I used a wrong input file, my bad, and this command gave an error in my terminal.

```
Error: Undefined mixin 'type'.
        on line 21 of app/sass/components/_components.booking-timeslot.scss, in `type'
        from line 21 of app/sass/components/_components.booking-timeslot.scss
```

The type mixin exists and I had to run 
`sass --precision 10 app/sass/main.scss app/main.css`
instead of 
`sass --precision 10 app/sass/**/* app/main.css` (in this case the mixin does not exist)

If I now run my gulp sass command, which worked fine before, this error still occur in my generated css output file, but my gulp sass command gives no errors.

main.css
```
body:before {
    white-space: pre;
    font-family: monospace;
    content: "Error: Undefined mixin 'type'.\A on line 21 of app/sass/components/_components.booking-timeslot.scss, in `type'\A from line 21 of app/sass/components/_components.booking-timeslot.scss\A \A 16: &__timeslot {\A 17: text-align: right;\A 18: }\A 19: \A 20: &__start-hour {\A 21: @include type('body', 'high emphasis');\A 22: }\A 23: \A 24: &__end-hour {\A 25: @include type('meta', 'medium emphasis');\A 26: }";
}
```

Can anyone explain what I am doing wrong or how I can undo the --precision command with the wrong input file?

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
