### ISSUE TITLE
Change SASS vars on button press

### ISSUE THREAD

**Issue by iamletigre** [sass/ruby-sass#83]
Back in the olden days when AOKP still used to be a thing with Android modders I visited `aokp.co` and they had a button to switch the color accents around completely. So, you press the button and shall we say everything that is black changes to pink.

Now I have an awesome Jekyll site located [here](https://github.com/iamletigre/iamletigre.github.io) and a feeble attempt to implement this functionality [here](https://github.com/iamletigre/sitecolors.js).
I do understand that Jekyll uses SASS and I created a partial for storing site-wide variables and now I am wondering how I can make a button that changes those site-wide variables defined in the `vars` partial without changing every single element's color in my javascript file. Any suggestions?
If the question is not entirely clear, please say so.

**Comment by iamletigre** [comment]
And any input will be greatly appreciated of course!

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.

**Comment by iamletigre** [comment]
@nex3 Yes but I got thrown out from SO because some people apparently take pleasure in making other people's lives hell! ;)
