### ISSUE TITLE
Generate comma-separated CSS selectors on separate lines

### ISSUE THREAD

**Issue by leosdad** [sass/ruby-sass#89]
Even using the expanded style, the following code:

    .ui-accordion-header {
        &.ui-state-default .ui-icon,
        &.ui-state-hover .ui-icon,
        &.ui-state-focus .ui-icon {
            left: 0;
        }
    }
will compile to:

    .ui-accordion-header.ui-state-default .ui-icon, .ui-accordion-header.ui-state-hover .ui-icon, .ui-accordion-header.ui-state-focus .ui-icon {
      left: 0;
    }
instead of:

    .ui-accordion-header.ui-state-default .ui-icon,
    .ui-accordion-header.ui-state-hover .ui-icon,
    .ui-accordion-header.ui-state-focus .ui-icon {
      left: 0;
    }
which would improve legibility quite a lot.

I suppose this would be possible to easy to achieve by tweaking to_css.rb, but unfortunately Ruby is not a language I'm familiar with.

I also suggest you consider providing more granular options like this one, line breaks after each selector, etc.

Thanks in advance, and congrats on the brilliant product.

**Comment by nex3** [comment]
I'm closing this issue as "on ice" because [Ruby Sass is deprecated](http://sass.logdown.com/posts/7081811) and no additional features are planned for it.
